export const FETCH_QUESTIONS = "QUESTIONS/FETCH";
export const FETCH_MORE_QUESTIONS = "QUESTIONS/FETCH_MORE";
export const FETCH_QUESTIONS_SUCCESS = "QUESTIONS/FETCH_SUCCESS";
export const FETCH_QUESTIONS_FAILURE = "QUESTIONS/FETCH_FAILURE";
export const SET_QUESTION = "QUESTIONS/SET_ACTIVE";
export const DELETE_QUESTION = "QUESTIONS/DELETE_QUESTION";
